### ISSUE TITLE
Segment write/read metrics not reported on committed transactions

### ISSUE THREAD

**Issue by jkhalack** [pravega/pravega#3692]
**Problem description**
When data is written to a stream (`<transaction-stream>`) in transactional writes, none of the following metrics is reported with the `stream` tag value  `<transaction-stream>`:
```
segmentstore.segment.write_bytes
segmentstore.segment.read_bytes
segmentstore.segment.write_events
```

I am sure that the data has been actually written and read from the stream, because:
- the `transactions_committed` metrics report non-zero values for this stream;
-  the client reports data being written and read from the stream
- the `segmentstore.segment.write_bytes_global`, `segmentstore.segment.read_bytes_global`,  and `segmentstore.segment.write_events_global` metrics report excess counts as compared to the totals of all scope/stream/segment read/write counts aggregated over pravega cluster.

The issue appeared when Micrometer metrics have been implemented.

**Problem location**
Segmentstore metrics

**Suggestions for an improvement**
Segmentstores should report segment read/write metrics on the parent segments after transactional writes have been committed to the stream.

**Comment by kevinhan88** [comment]
For troubleshooting purpose: 0.5.0-2154.f65a978 works reporting the above metrics; 0.5.0-2222.8ba5431 didn't.

**Comment by kevinhan88** [comment]
Per my local test, it's verified the issue was caused by backward compatibility issue with WireCommands.
The issue has been fixed with https://github.com/pravega/pravega/pull/3640, but the underlying Pravega version of Client must include this commit:

commit cb253c8c73b076adbe76cd87da8418c09a8989b3
Author: Tom Kaitchuck <tkaitchuck@users.noreply.github.com>
Date:   Thu Apr 18 00:33:20 2019 -0700
    Issue #3624: Fix backward compatibility issue with WireCommands. (#3640)
    * Removes unneeded requestId on AppendBlock.

**Comment by kevinhan88** [comment]
As it is a general perception that Pravega client is backwards compatible, at least with the same minor version (e.g. 0.5.0), so it is necessary to make it aware to the teams to sync up the underlying Pravega versions in their test env.

**Comment by jkhalack** [comment]
Tried running the same code with the latest version of pravega (version `0.6.0-2233.148289d` both for server and the client).

Still don't see any segmentstore metrics on the streams that have transactional writes.
Moreover, any existing stream-tagged segmentstore metrics stop being reported with the start of transactional writes (see 11:31 time point in the charts below):

![metrics_switch](https://user-images.githubusercontent.com/25368596/56821971-144ac080-6826-11e9-9764-49d6e36040b7.png)

Seeing this error in the segmentstore logs :
```
2019-04-26 15:51:47,025 7261747 [epollEventLoopGroup-11-2] INFO  i.p.s.s.h.handler.AppendProcessor - Received hello from connection: [id: 0x72fb7a55, L:/172.24.58.15:12345 - R:/172.24.178.3:35322]
2019-04-26 15:51:47,025 7261747 [epollEventLoopGroup-11-2] INFO  i.p.s.s.h.handler.AppendProcessor - Setting up appends for writer: 4723c50d-a30f-4817-82c1-16ff4b36159b on segment: longevity/smallScale/8.#epoch.4
2019-04-26 15:51:47,044 7261766 [epollEventLoopGroup-11-1] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=401405] Fetching keys from WireCommands.ReadTableKeys(type=READ_TABLE_KEYS, requestId=401405, segment=_system/_tables/longevity/tiny/epochsWithTransactions.#.4091a1b9-3c40-4cd2-87c0-9c4401af832d, delegationToken=, suggestedKeyCount=1000, continuationToken=EmptyByteBufBE).
2019-04-26 15:51:47,045 7261767 [epollEventLoopGroup-11-1] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=401406] Fetching keys from WireCommands.ReadTableKeys(type=READ_TABLE_KEYS, requestId=401406, segment=_system/_tables/longevity/tiny/epochsWithTransactions.#.4091a1b9-3c40-4cd2-87c0-9c4401af832d, delegationToken=, suggestedKeyCount=1000, continuationToken=UnpooledHeapByteBuf(ridx: 0, widx: 24, cap: 24/24)).
2019-04-26 15:51:47,056 7261778 [epollEventLoopGroup-11-1] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=401415] Fetching keys from WireCommands.ReadTableKeys(type=READ_TABLE_KEYS, requestId=401415, segment=_system/_tables/longevity/tiny/epochsWithTransactions.#.4091a1b9-3c40-4cd2-87c0-9c4401af832d, delegationToken=, suggestedKeyCount=1000, continuationToken=EmptyByteBufBE).
2019-04-26 15:51:47,060 7261782 [epollEventLoopGroup-11-2] INFO  i.p.s.s.h.h.PravegaRequestProcessor - [requestId=401419] Fetching keys from WireCommands.ReadTableKeys(type=READ_TABLE_KEYS, requestId=401419, segment=_system/_tables/longevity/tiny/epochsWithTransactions.#.4091a1b9-3c40-4cd2-87c0-9c4401af832d, delegationToken=, suggestedKeyCount=1000, continuationToken=UnpooledHeapByteBuf(ridx: 0, widx: 24, cap: 24/24)).
2019-04-26 15:51:47,128 7261850 [epollEventLoopGroup-11-2] ERROR i.p.s.s.h.h.ServerConnectionInboundHandler - Caught exception on connection: 
io.netty.handler.codec.DecoderException: io.pravega.shared.protocol.netty.InvalidMessageException: AppendBlockEnd without AppendBlock.
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
```

**Comment by RaulGracia** [comment]
@shrids @tkaitchuck wasn't this issue addressed with #3640 and/or #3615?

**Comment by jkhalack** [comment]
The issue is still present on version `0.6.0-2233.148289d` and on `PR-3720-0.5.0-2236.1371471`.

I did a little experimenting, and the segments seem to be excluded from reporting kind of sporadically.
I never see the segmentstore metrics on the streams with fixed number of segments.
For the streams with dynamic scaling, some segments are being reported, the others are not.
